#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/oddevan/laptop/oddevan/mac
curl --remote-name https://raw.githubusercontent.com/oddevan/laptop/oddevan/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
